<a href="https://colab.research.google.com/github/Meghashyamt/python/blob/master/PrincipleComponentAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Principle Component Analysis

In [0]:
#
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sb
%matplotlib inline

from sklearn.preprocessing import scale
from sklearn.preprocessing import normalize

#model
from sklearn.decomposition import PCA

In [22]:
data=pd.read_excel("universitynew.xlsx")
data.head()

,University,SAT,Top10,Accept,SFRatio,Expenses,GradRate
0,Harvard University,1310,89,22,13,22704,94
1,California Institute of Technology,1415,100,25,6,63575,81
2,Massachusetts Institute of Technology,1260,62,59,9,25026,72
3,Stanford University,1310,76,24,12,31510,88
4,Princeton University,1280,83,33,13,21864,90

In [23]:
data1=data.iloc[:,1:]
data1.head()

    SAT  Top10  Accept  SFRatio  Expenses  GradRate
0  1310     89      22       13     22704        94
1  1415    100      25        6     63575        81
2  1260     62      59        9     25026        72
3  1310     76      24       12     31510        88
4  1280     83      33       13     21864        90

In [29]:
data1= scale(data1)
data1

array([[ 6.32860277e-01,  1.50011672e+00, -8.47758804e-01,
        -1.06559813e+00, -1.49953373e+00,  1.21638361e+00],
       [ 2.80231274e+00,  3.69443640e+00, -3.36033168e-01,
        -2.18224287e+00,  1.29812886e+00, -1.28171859e+00],
       [-4.00212326e-01, -3.88594066e+00,  5.46352405e+00,
        -1.70368084e+00, -1.34059041e+00, -3.01117396e+00],
       [ 6.32860277e-01, -1.09317017e+00, -5.06608380e-01,
        -1.22511881e+00, -8.96753843e-01,  6.34133635e-02],
       [ 1.30167148e-02,  3.03215082e-01,  1.02856853e+00,
        -1.06559813e+00, -1.55703261e+00,  4.47736779e-01],
       [ 1.45931836e+00, -4.94719345e-01, -8.47758804e-01,
         1.64625339e+00, -1.56606814e+00, -3.20910052e-01],
       [ 2.49239096e+00,  5.02698689e-01, -3.36033168e-01,
         5.29608650e-01,  4.98073064e-01,  8.32060194e-01],
       [ 1.25270384e+00, -6.94202952e-01, -3.36033168e-01,
        -1.08474061e-01, -1.22169095e+00, -8.97395175e-01],
       [-1.24733186e+00, -8.93686559e-01, -1.53005965e+00,
         6.89129328e-01, -3.96098807e-02,  1.40854532e+00],
       [ 5.08891564e-01, -1.09317017e+00,  5.11725637e-03,
         5.29608650e-01,  8.77775107e-02,  1.40854532e+00],
       [-1.45394638e+00,  5.02698689e-01,  1.02856853e+00,
         5.29608650e-01, -7.67244470e-01, -5.13071760e-01],
       [-1.53659219e+00, -1.29265377e+00,  1.75692469e-01,
         6.89129328e-01,  9.25823633e-01, -3.20910052e-01],
       [-9.16748628e-01,  9.01665903e-01,  5.11725637e-03,
         8.48650006e-01, -4.84404759e-01, -1.08955688e+00],
       [-6.68811203e-01,  3.03215082e-01, -1.65457956e-01,
         1.32721204e+00,  9.12475679e-01,  4.47736779e-01],
       [-1.14402460e+00, -9.57521313e-02, -1.65457956e-01,
         5.29608650e-01,  7.93439315e-01,  1.21638361e+00],
       [-8.96087176e-01, -1.09317017e+00,  8.57993317e-01,
        -1.38463948e+00, -4.98847929e-01, -1.08955688e+00],
       [ 5.70875920e-01, -4.94719345e-01, -1.01833402e+00,
         3.70087972e-01, -1.48604887e+00, -1.08955688e+00],
       [-2.34920710e-01, -1.09317017e+00, -1.35948444e+00,
         1.48673272e+00, -5.18288026e-01,  1.40854532e+00],
       [ 2.81615592e-01, -6.94202952e-01, -5.06608380e-01,
        -1.08474061e-01,  1.64709227e+00,  6.34133635e-02],
       [ 2.60954139e-01,  5.02698689e-01, -6.77183592e-01,
         5.10466169e-02, -1.19964971e+00, -1.28171859e+00],
       [-1.37130057e+00, -1.09317017e+00, -6.77183592e-01,
        -1.38463948e+00,  1.52607083e+00, -8.97395175e-01],
       [ 2.60954139e-01,  5.02698689e-01, -8.47758804e-01,
         2.10567295e-01, -1.45983212e+00, -1.28171859e+00],
       [-4.82858135e-01,  1.10114951e+00,  5.16842893e-01,
         5.29608650e-01, -1.39199714e+00, -5.13071760e-01],
       [-2.55582162e-01,  1.10114951e+00, -1.65457956e-01,
         8.48650006e-01,  5.11626370e-01,  1.02422190e+00],
       [ 1.31468819e+00,  7.02182296e-01,  1.19914374e+00,
         5.10466169e-02,  4.61520207e-01, -5.13071760e-01],
       [-1.52274902e-01,  9.01665903e-01, -1.01833402e+00,
        -4.27515416e-01, -5.86739069e-01,  4.47736779e-01],
       [-1.61923800e+00, -6.94202952e-01, -1.18890923e+00,
         2.10567295e-01,  9.53796836e-03,  8.32060194e-01],
       [ 1.45931836e+00, -9.57521313e-02,  5.16842893e-01,
         2.10567295e-01,  4.50841844e-01, -3.20910052e-01],
       [ 1.14939658e+00,  7.02182296e-01,  1.75692469e-01,
        -2.67994739e-01, -9.13113643e-01, -8.97395175e-01],
       [-1.22667041e+00,  7.02182296e-01, -8.47758804e-01,
        -1.54416016e+00,  1.60465263e+00,  1.21638361e+00],
       [ 1.19071948e+00,  9.01665903e-01,  5.11725637e-03,
        -2.67994739e-01,  1.34583923e+00, -1.28171859e+00],
       [ 1.10807367e+00,  1.03731476e-01,  1.75692469e-01,
         1.16769136e+00, -8.41993009e-01,  6.34133635e-02],
       [ 1.33534965e+00,  5.02698689e-01,  1.75692469e-01,
        -9.06077450e-01,  9.01732972e-02,  4.47736779e-01],
       [ 1.98969783e-01,  1.03731476e-01,  8.57993317e-01,
         1.00817068e+00,  7.76737260e-01, -1.47388030e+00],
       [-1.37130057e+00, -1.09317017e+00,  1.36971895e+00,
        -1.22511881e+00, -7.29870200e-01,  6.34133635e-02],
       [ 6.74183181e-01,  1.50011672e+00, -1.01833402e+00,
        -1.54416016e+00,  1.54749601e+00, -1.28748344e-01],
       [-1.53659219e+00, -1.29265377e+00,  1.75692469e-01,
         5.29608650e-01,  5.12310881e-01, -1.28748344e-01],
       [-8.96087176e-01, -4.94719345e-01,  5.16842893e-01,
         8.48650006e-01, -1.32429495e-01,  1.60070703e+00],
       [ 1.29402674e+00, -8.93686559e-01,  5.11725637e-03,
        -1.22511881e+00,  1.10208507e+00, -1.08955688e+00],
       [-2.96905066e-01, -6.94202952e-01, -1.53005965e+00,
        -1.22511881e+00,  1.41559085e+00, -8.97395175e-01],
       [-1.43328493e+00,  3.03215082e-01, -1.53005965e+00,
         1.32721204e+00,  1.40778743e+00, -7.05233467e-01],
       [ 9.63443509e-01, -2.95235738e-01, -6.77183592e-01,
        -4.27515416e-01, -4.03221822e-01,  2.55575071e-01],
       [-8.75425724e-01,  9.01665903e-01,  1.36971895e+00,
        -2.67994739e-01, -2.92194230e-01,  2.55575071e-01],
       [-8.96087176e-01,  3.03215082e-01,  5.11725637e-03,
         1.32721204e+00,  1.39840963e+00,  1.40854532e+00],
       [ 1.19071948e+00,  7.02182296e-01,  5.11725637e-03,
         1.16769136e+00, -1.24400599e+00,  2.55575071e-01],
       [-8.34102820e-01,  9.01665903e-01, -5.06608380e-01,
        -9.06077450e-01, -2.57694904e-01, -1.28171859e+00],
       [-5.86165395e-01,  1.30063312e+00, -1.65457956e-01,
         5.10466169e-02,  1.38567774e+00, -3.20910052e-01],
       [-1.30931622e+00,  7.02182296e-01,  1.02856853e+00,
        -1.06559813e+00,  1.18374716e+00, -5.13071760e-01],
       [-5.44842491e-01, -1.29265377e+00,  1.02856853e+00,
         5.29608650e-01,  1.60088782e+00,  2.55575071e-01],
       [ 5.43396189e-02,  1.10114951e+00,  6.87418105e-01,
        -9.06077450e-01, -3.70639126e-01, -1.08955688e+00],
       [ 8.18813345e-01, -2.95235738e-01, -1.35948444e+00,
         1.64625339e+00, -1.97800241e-01, -1.28748344e-01],
       [ 5.50214468e-01,  1.10114951e+00,  1.19914374e+00,
        -7.46556772e-01,  1.11748655e+00, -7.05233467e-01],
       [-1.06137879e+00, -6.94202952e-01, -1.35948444e+00,
         6.89129328e-01, -3.28541734e-01,  1.40854532e+00],
       [-4.82858135e-01, -1.29265377e+00, -5.06608380e-01,
         5.10466169e-02,  1.26985858e+00,  6.39898487e-01],
       [-7.30795559e-01,  9.01665903e-01, -1.01833402e+00,
        -7.46556772e-01, -1.51787861e+00, -8.97395175e-01],
       [-3.17566518e-01,  5.02698689e-01, -1.01833402e+00,
         1.48673272e+00, -1.80892834e-01,  1.40854532e+00],
       [-1.93597806e-01,  1.10114951e+00,  1.36971895e+00,
         5.29608650e-01, -5.88108090e-01, -1.28171859e+00],
       [ 7.50010710e-02, -2.95235738e-01,  1.19914374e+00,
         2.10567295e-01, -1.47345388e+00,  1.21638361e+00],
       [ 1.35601110e+00, -1.29265377e+00, -6.77183592e-01,
        -1.54416016e+00,  8.44572244e-01, -1.08955688e+00],
       [-4.89676414e-02,  1.10114951e+00, -8.47758804e-01,
         1.16769136e+00,  9.24317710e-01,  6.39898487e-01],
       [-1.72936354e-01, -1.29265377e+00,  5.16842893e-01,
        -1.06559813e+00,  4.17574637e-01,  1.40854532e+00],
       [ 5.43396189e-02, -2.95235738e-01,  8.57993317e-01,
         1.32721204e+00, -1.43723917e-01, -1.08955688e+00],
       [-1.37130057e+00, -8.93686559e-01, -1.65457956e-01,
        -7.46556772e-01,  1.51019019e+00,  1.21638361e+00],
       [ 8.18813345e-01, -6.94202952e-01,  5.16842893e-01,
        -1.54416016e+00, -2.93631702e-01,  2.55575071e-01],
       [ 4.05584304e-01, -8.93686559e-01,  8.57993317e-01,
         1.64625339e+00, -1.15679936e+00, -1.28748344e-01],
       [-9.78732984e-01,  7.02182296e-01, -5.06608380e-01,
        -1.06559813e+00, -1.73632916e-02,  2.55575071e-01],
       [-1.59857655e+00, -9.57521313e-02, -1.18890923e+00,
        -1.22511881e+00, -3.39630803e-01,  1.02422190e+00],
       [-2.34920710e-01, -2.95235738e-01,  5.16842893e-01,
         1.48673272e+00, -7.12552086e-01,  1.02422190e+00],
       [ 1.10807367e+00, -1.09317017e+00,  1.02856853e+00,
         6.89129328e-01, -1.00599760e-01,  8.32060194e-01],
       [ 1.19071948e+00,  1.03731476e-01,  1.19914374e+00,
        -1.38463948e+00,  1.08442470e+00,  8.32060194e-01],
       [-3.79550874e-01,  1.50011672e+00,  6.87418105e-01,
         1.00817068e+00, -1.47680798e+00, -1.28748344e-01],
       [ 1.25270384e+00,  1.03731476e-01, -1.65457956e-01,
         1.32721204e+00,  1.50204451e+00,  6.39898487e-01],
       [ 7.98151893e-01, -4.94719345e-01, -1.53005965e+00,
         3.70087972e-01,  3.97381579e-01, -1.28171859e+00],
       [-7.10134107e-01, -6.94202952e-01,  5.11725637e-03,
        -4.27515416e-01,  7.91591137e-01, -5.13071760e-01],
       [ 1.43865691e+00,  1.10114951e+00,  5.16842893e-01,
         5.10466169e-02, -1.52725640e+00, -1.28748344e-01],
       [-1.43328493e+00, -1.09317017e+00,  1.75692469e-01,
        -9.06077450e-01, -3.19232392e-01, -1.08955688e+00],
       [-2.83061893e-02, -8.93686559e-01,  6.87418105e-01,
         6.89129328e-01,  1.35275279e+00,  1.60070703e+00],
       [ 1.06675077e+00,  1.10114951e+00,  3.46267681e-01,
         1.48673272e+00, -6.23360377e-01, -1.47388030e+00],
       [ 1.00476641e+00, -1.29265377e+00,  8.57993317e-01,
         5.29608650e-01,  9.32394933e-01,  6.39898487e-01],
       [ 1.39733400e+00,  1.50011672e+00, -6.77183592e-01,
        -2.67994739e-01, -7.59167247e-01,  1.40854532e+00],
       [-3.58889422e-01,  9.01665903e-01,  1.02856853e+00,
         1.32721204e+00, -1.36906604e+00, -5.13071760e-01],
       [-6.89472655e-01,  1.10114951e+00, -3.36033168e-01,
        -1.38463948e+00,  1.00029837e+00,  4.47736779e-01],
       [ 5.50214468e-01, -8.93686559e-01,  1.36971895e+00,
        -1.38463948e+00,  1.31893797e+00, -1.08955688e+00],
       [ 4.46907208e-01, -2.95235738e-01,  1.75692469e-01,
         6.89129328e-01,  6.12728561e-01, -5.13071760e-01],
       [-1.28865476e+00, -6.94202952e-01, -3.36033168e-01,
        -1.22511881e+00, -4.57366597e-01, -1.28171859e+00],
       [-8.75425724e-01, -1.09317017e+00,  1.19914374e+00,
        -7.46556772e-01, -5.85164695e-01, -1.28171859e+00],
       [ 1.78308331e-01, -9.57521313e-02,  5.11725637e-03,
        -9.06077450e-01, -1.36653335e+00,  2.55575071e-01],
       [-3.38227970e-01,  1.10114951e+00,  3.46267681e-01,
        -1.22511881e+00, -7.98663499e-01, -8.97395175e-01],
       [ 7.50010710e-02,  1.03731476e-01,  8.57993317e-01,
        -9.06077450e-01,  1.73204413e-01, -1.08955688e+00],
       [-5.65503943e-01, -4.94719345e-01, -5.06608380e-01,
         1.64625339e+00,  6.86837767e-03,  4.47736779e-01],
       [-1.08204024e+00,  3.03215082e-01, -1.53005965e+00,
         2.10567295e-01, -1.53834547e+00, -3.20910052e-01],
       [ 3.64261400e-01, -6.94202952e-01, -1.35948444e+00,
         1.00817068e+00,  4.51731707e-01,  1.40854532e+00],
       [ 1.17005803e+00,  1.03731476e-01, -6.77183592e-01,
         5.29608650e-01,  6.23406924e-01, -1.28748344e-01],
       [-5.65503943e-01,  1.30063312e+00, -8.47758804e-01,
         1.16769136e+00,  1.31791121e+00,  1.60070703e+00],
       [ 4.05584304e-01,  7.02182296e-01,  1.36971895e+00,
        -1.06559813e+00, -9.26872302e-01,  2.55575071e-01],
       [-1.18534750e+00, -1.09317017e+00, -1.01833402e+00,
         5.10466169e-02, -1.27131795e+00,  1.02422190e+00],
       [-9.78732984e-01, -2.95235738e-01,  3.46267681e-01,
         3.70087972e-01, -1.15179832e-01,  1.60070703e+00],
       [ 1.37667255e+00, -2.95235738e-01, -1.65457956e-01,
        -4.27515416e-01,  9.41362019e-01, -1.47388030e+00],
       [-5.86165395e-01,  9.01665903e-01,  1.75692469e-01,
         6.89129328e-01, -1.40096423e+00,  1.60070703e+00],
       [ 1.43865691e+00,  1.03731476e-01, -1.18890923e+00,
         5.10466169e-02,  2.00927085e-01,  1.02422190e+00]])

In [0]:
data1=pd.DataFrame(data1)

In [26]:
data1.head()

          0         1         2         3         4         5
0  0.632860  1.500117 -0.847759 -1.065598 -1.499534  1.216384
1  2.802313  3.694436 -0.336033 -2.182243  1.298129 -1.281719
2 -0.400212 -3.885941  5.463524 -1.703681 -1.340590 -3.011174
3  0.632860 -1.093170 -0.506608 -1.225119 -0.896754  0.063413
4  0.013017  0.303215  1.028569 -1.065598 -1.557033  0.447737

In [0]:
model=PCA()

In [28]:
model.fit(data1)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [31]:
model.components_

array([[ 0.10540976, -0.18438361,  0.58125243, -0.47450123, -0.13493754,
        -0.61129169],
       [ 0.65920969,  0.6920139 , -0.17804806, -0.05368063, -0.11374753,
        -0.19758067],
       [-0.00126588,  0.0387435 , -0.2212484 , -0.51382021,  0.82794735,
        -0.00620183],
       [-0.63664663,  0.41283798, -0.2887001 , -0.44191458, -0.37231631,
        -0.0836074 ],
       [-0.04557567, -0.27961619, -0.57958081,  0.28939417,  0.03244143,
        -0.70641511],
       [ 0.3833193 , -0.48682437, -0.40278033, -0.47845406, -0.3790576 ,
         0.28501473]])

In [0]:
component = pd.DataFrame(model.components_)

In [33]:
component.head()

          0         1         2         3         4         5
0  0.105410 -0.184384  0.581252 -0.474501 -0.134938 -0.611292
1  0.659210  0.692014 -0.178048 -0.053681 -0.113748 -0.197581
2 -0.001266  0.038744 -0.221248 -0.513820  0.827947 -0.006202
3 -0.636647  0.412838 -0.288700 -0.441915 -0.372316 -0.083607
4 -0.045576 -0.279616 -0.579581  0.289394  0.032441 -0.706415

In [0]:
value=model.explained_variance_ratio_

In [35]:
value

array([0.25857915, 0.21110352, 0.18220855, 0.13982004, 0.10506738,
       0.10322136])

In [36]:
value.sum()

1.0