<a href="https://colab.research.google.com/github/Meghashyamt/python/blob/master/sfsalarypracexercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [0]:
sal= pd.read_csv("Salaries.csv")

In [8]:
sal.head(300)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011.0,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011.0,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011.0,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011.0,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011.0,NaN,San Francisco,NaN
5,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602.00,8601.00,189082.74,NaN,316285.74,316285.74,2011.0,NaN,San Francisco,NaN
6,7,ALSON LEE,"BATTALION CHIEF, (FIRE DEPARTMENT)",92492.01,89062.90,134426.14,NaN,315981.05,315981.05,2011.0,NaN,San Francisco,NaN
7,8,DAVID KUSHNER,DEPUTY DIRECTOR OF INVESTMENTS,256576.96,0.00,51322.50,NaN,307899.46,307899.46,2011.0,NaN,San Francisco,NaN
8,9,MICHAEL MORRIS,"BATTALION CHIEF, (FIRE DEPARTMENT)",176932.64,86362.68,40132.23,NaN,303427.55,303427.55,2011.0,NaN,San Francisco,NaN
9,10,JOANNE HAYES-WHITE,"CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",285262.00,0.00,17115.73,NaN,302377.73,302377.73,2011.0,NaN,San Francisco,NaN
10,11,ARTHUR KENNEY,"ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",194999.39,71344.88,33149.90,NaN,299494.17,299494.17,2011.0,NaN,San Francisco,NaN
11,12,PATRICIA JACKSON,CAPTAIN III (POLICE DEPARTMENT),99722.00,87082.62,110804.30,NaN,297608.92,297608.92,2011.0,NaN,San Francisco,NaN
12,13,EDWARD HARRINGTON,EXECUTIVE CONTRACT EMPLOYEE,294580.02,0.00,0.00,NaN,294580.02,294580.02,2011.0,NaN,San Francisco,NaN
13,14,JOHN MARTIN,DEPARTMENT HEAD V,271329.03,0.00,21342.59,NaN,292671.62,292671.62,2011.0,NaN,San Francisco,NaN
14,15,DAVID FRANKLIN,"BATTALION CHIEF, (FIRE DEPARTMENT)",174872.64,74050.30,37424.11,NaN,286347.05,286347.05,2011.0,NaN,San Francisco,NaN
15,16,RICHARD CORRIEA,"COMMANDER III, (POLICE DEPARTMENT)",198778.01,73478.20,13957.65,NaN,286213.86,286213.86,2011.0,NaN,San Francisco,NaN
16,17,AMY HART,DEPARTMENT HEAD V,268604.57,0.00,16115.86,NaN,284720.43,284720.43,2011.0,NaN,San Francisco,NaN
17,18,SEBASTIAN WONG,"CAPTAIN, EMERGENCYCY MEDICAL SERVICES",140546.87,119397.26,18625.08,NaN,278569.21,278569.21,2011.0,NaN,San Francisco,NaN
18,19,MARTY ROSS,"BATTALION CHIEF, (FIRE DEPARTMENT)",168692.63,69626.12,38115.47,NaN,276434.22,276434.22,2011.0,NaN,San Francisco,NaN
19,20,ELLEN MOFFATT,ASSISTANT MEDICAL EXAMINER,257510.59,880.16,16159.50,NaN,274550.25,274550.25,2011.0,NaN,San Francisco,NaN
20,21,VENUS AZAR,ASSISTANT MEDICAL EXAMINER,257510.48,0.00,16679.79,NaN,274190.27,274190.27,2011.0,NaN,San Francisco,NaN
21,22,JUDY MELINEK,ASSISTANT MEDICAL EXAMINER,257510.44,377.21,15883.56,NaN,273771.21,273771.21,2011.0,NaN,San Francisco,NaN
22,23,GEORGE GARCIA,"CAPTAIN, FIRE SUPPRESSION",140546.88,93200.58,39955.25,NaN,273702.71,273702.71,2011.0,NaN,San Francisco,NaN
23,24,VICTOR WYRSCH,"BATTALION CHIEF, (FIRE DEPARTMENT)",168692.63,77896.14,24083.86,NaN,270672.63,270672.63,2011.0,NaN,San Francisco,NaN
24,25,JOSEPH DRISCOLL,"CAPTAIN, FIRE SUPPRESSION",140546.86,97868.77,31909.28,NaN,270324.91,270324.91,2011.0,NaN,San Francisco,NaN
25,26,GREGORY SUHR,CHIEF OF POLICE,256470.41,0.00,11522.18,NaN,267992.59,267992.59,2011.0,NaN,San Francisco,NaN
26,27,JOHN HANLEY,"CAPTAIN, FIRE SUPPRESSION",92080.80,40008.00,133695.76,NaN,265784.56,265784.56,2011.0,NaN,San Francisco,NaN
27,28,RAYMOND GUZMAN,"BATTALION CHIEF, (FIRE DEPARTMENT)",168692.59,80706.88,16063.99,NaN,265463.46,265463.46,2011.0,NaN,San Francisco,NaN
28,29,DENISE SCHMITT,DEPUTY CHIEF III (POLICE DEPARTMENT),261717.60,0.00,2357.00,NaN,264074.60,264074.60,2011.0,NaN,San Francisco,NaN
29,30,MONICA FIELDS,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",246225.60,0.00,15140.54,NaN,261366.14,261366.14,2011.0,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,271,ARNIE LEE,FIREFIGHTER,105934.66,75817.75,17540.56,NaN,199292.97,199292.97,2011.0,NaN,San Francisco,NaN
271,272,DENNIS MARTINEZ,POLICE OFFICER III,112401.06,45977.26,40829.52,NaN,199207.84,199207.84,2011.0,NaN,San Francisco,NaN
272,273,MITCHELL LEE,FIREFIGHTER,105934.65,76012.89,17180.05,NaN,199127.59,199127.59,2011.0,NaN,San Francisco,NaN
273,274,FERDINAND CADELINA,TRANSIT SUPERVISOR,88400.70,107913.65,2713.83,NaN,199028.18,199028.18,2011.0,NaN,San Francisco,NaN
274,275,DENIS OLEARY,CAPTAIN III (POLICE DEPARTMENT),188341.60,0.00,10542.72,NaN,198884.32,198884.32,2011.0,NaN,San Francisco,NaN
275,276,NEREE DASTOUS,FIREFIGHTER,105934.66,73625.33,19217.48,NaN,198777.47,198777.47,2011.0,NaN,San Francisco,NaN
276,277,PERRY LEONG,ELECTRICAL TRANSIT SYSTEM MECHANIC,77580.41,113729.55,7308.25,NaN,198618.21,198618.21,2011.0,NaN,San Francisco,NaN
277,278,LOUIS CASSANEGO,CAPTAIN III (POLICE DEPARTMENT),188341.60,0.00,10125.04,NaN,198466.64,198466.64,2011.0,NaN,San Francisco,NaN
278,279,MELISSA LERMA,"INSPECTOR, BUREAU OF FIRE PREVENTION AND PUBLI...",126968.08,1706.08,69787.98,NaN,198462.14,198462.14,2011.0,NaN,San Francisco,NaN
279,280,RAYMOND CHAVEZ,FIREFIGHTER,105934.66,70730.50,21611.32,NaN,198276.48,198276.48,2011.0,NaN,San Francisco,NaN
280,281,FREDERICK BINKLEY,FIRE FIGHTER PARAMEDIC,122404.96,60981.91,14860.06,NaN,198246.93,198246.93,2011.0,NaN,San Francisco,NaN
281,282,GUY GOODWIN,FIRE FIGHTER PARAMEDIC,122404.98,67825.92,7933.55,NaN,198164.45,198164.45,2011.0,NaN,San Francisco,NaN
282,283,JEFFREY ADACHI,PUBLIC DEFENDER,198027.44,0.00,0.00,NaN,198027.44,198027.44,2011.0,NaN,San Francisco,NaN
283,284,BERGLIOTH MATHEWS,"LIEUTENANT, FIRE DEPARTMENT",123105.02,67514.41,7386.30,NaN,198005.73,198005.73,2011.0,NaN,San Francisco,NaN
284,285,GARRET TOM,CAPTAIN III (POLICE DEPARTMENT),188341.62,2886.03,6646.21,NaN,197873.86,197873.86,2011.0,NaN,San Francisco,NaN
285,286,JAMES MILLER,LIEUTENANT III (POLICE DEPARTMENT),149044.41,35620.45,13162.31,NaN,197827.17,197827.17,2011.0,NaN,San Francisco,NaN
286,287,PAUL LEE,TRANSIT SUPERVISOR,89930.37,104568.19,3312.11,NaN,197810.67,197810.67,2011.0,NaN,San Francisco,NaN
287,288,TANGERINE BRIGHAM,DEPUTY DIRECTOR V,185724.50,0.00,12000.00,NaN,197724.50,197724.50,2011.0,NaN,San Francisco,NaN
288,289,PABLO SIGUENZA,"LIEUTENANT, FIRE DEPARTMENT",128569.01,49853.04,19031.08,NaN,197453.13,197453.13,2011.0,NaN,San Francisco,NaN
289,290,DANIEL CUNNINGHAM,"INSPECTOR III, (POLICE DEPARTMENT)",130466.59,44651.56,22315.92,NaN,197434.07,197434.07,2011.0,NaN,San Francisco,NaN
290,291,JIMMIE LEW,"INSPECTOR III, (POLICE DEPARTMENT)",130481.57,39489.61,27451.83,NaN,197423.01,197423.01,2011.0,NaN,San Francisco,NaN
291,292,DEBBIE TAM,NURSING SUPERVISOR,190243.46,0.00,7105.58,NaN,197349.04,197349.04,2011.0,NaN,San Francisco,NaN
292,293,ALBERT YU,SUPERVISING PHYSICIAN SPECIALIST,192379.60,0.00,4891.00,NaN,197270.60,197270.60,2011.0,NaN,San Francisco,NaN
293,294,MICHAEL HENNESSEY,SHERIFF,197233.84,0.00,0.00,NaN,197233.84,197233.84,2011.0,NaN,San Francisco,NaN
294,295,BRIAN MURPHY,FIREFIGHTER,105934.65,68438.92,22759.89,NaN,197133.46,197133.46,2011.0,NaN,San Francisco,NaN
295,296,STEVEN WILLIAMS,FIREFIGHTER,113695.71,69419.29,14017.12,NaN,197132.12,197132.12,2011.0,NaN,San Francisco,NaN
296,297,DAVID LAZAR,CAPTAIN III (POLICE DEPARTMENT),195975.32,0.00,917.32,NaN,196892.64,196892.64,2011.0,NaN,San Francisco,NaN
297,298,JOSEPHINE RAPADAS,NURSE MANAGER,171071.36,7606.83,18210.20,NaN,196888.39,196888.39,2011.0,NaN,San Francisco,NaN
298,299,JAMES HARRIGAN,CHIEF ATTORNEY I (CIVIL & CRIMINAL),196886.55,0.00,0.00,NaN,196886.55,196886.55,2011.0,NaN,San Francisco,NaN
299,300,JOANNE HOEPER,CHIEF ATTORNEY I (CIVIL & CRIMINAL),196886.55,0.00,0.00,NaN,196886.55,196886.55,2011.0,NaN,San Francisco,NaN

In [9]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30362 entries, 0 to 30361
Data columns (total 13 columns):
Id                  30362 non-null int64
EmployeeName        30361 non-null object
JobTitle            30361 non-null object
BasePay             30361 non-null float64
OvertimePay         30361 non-null float64
OtherPay            30361 non-null float64
Benefits            0 non-null float64
TotalPay            30361 non-null float64
TotalPayBenefits    30361 non-null float64
Year                30361 non-null float64
Notes               0 non-null float64
Agency              30361 non-null object
Status              0 non-null float64
dtypes: float64(9), int64(1), object(3)
memory usage: 3.0+ MB

In [10]:
sal['BasePay'].mean()

74696.90481835336

In [11]:
sal['OvertimePay'].max()

245131.88

In [12]:
df = sal[sal.EmployeeName == 'JOSEPH DRISCOLL']
df.loc[:,'JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

In [13]:
df = sal[sal.EmployeeName == 'JOSEPH DRISCOLL']
df.loc[:,'TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

In [0]:
#df = sal['TotalPay'].max()
#df.loc[:,'EmployeeName']

In [15]:
df=sal['EmployeeName'][sal.TotalPay==sal.TotalPay.max()]
df

0    NATHANIEL FORD
Name: EmployeeName, dtype: object

In [16]:
df =sal[(sal.Year>=2011) & (sal.Year>=2014)]
df.loc[:,('BasePay')]

Series([], Name: BasePay, dtype: float64)

In [17]:
sum(sal[sal['Year'] == 2013]['JobTitle'].value_counts() == 1)

0

In [0]:
def chief_string(title):
if 'chief' in title.lower().split():
return True
elif 'chief,' in title.lower().split():
return True
else:
return False

In [18]:
comm= pd.read_csv("Ecommerce Purchases.csv")
comm.head()

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82

In [19]:
comm.shape

(10000, 14)

In [20]:
comm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
Address             10000 non-null object
Lot                 10000 non-null object
AM or PM            10000 non-null object
Browser Info        10000 non-null object
Company             10000 non-null object
Credit Card         10000 non-null int64
CC Exp Date         10000 non-null object
CC Security Code    10000 non-null int64
CC Provider         10000 non-null object
Email               10000 non-null object
Job                 10000 non-null object
IP Address          10000 non-null object
Language            10000 non-null object
Purchase Price      10000 non-null float64
dtypes: float64(1), int64(2), object(11)
memory usage: 1.1+ MB

In [21]:
comm['Purchase Price'].mean()

50.34730200000025

In [22]:
comm['Purchase Price'].max()

99.99

In [23]:
comm['Purchase Price'].min()

0.0

In [25]:
comm[comm['Language']=='en'].count()

Address             1098
Lot                 1098
AM or PM            1098
Browser Info        1098
Company             1098
Credit Card         1098
CC Exp Date         1098
CC Security Code    1098
CC Provider         1098
Email               1098
Job                 1098
IP Address          1098
Language            1098
Purchase Price      1098
dtype: int64